[profile.default]
  evm_version = "paris"
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 200
  out = "artifacts"
  remappings = [
  '@superfluid-finance/ethereum-contracts/=lib/protocol-monorepo/packages/ethereum-contracts/',
  'forge-std/=lib/forge-std/src/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@uniswap/v3-periphery/=lib/v3-periphery/',
  '@uniswap/v3-core/=lib/v3-core/',
  '@gelato/=lib/ops/',
  '@chainlink/contracts/=lib/chainlink/contracts/src/v0.8/shared/',
  ]
  solc_version = "0.8.26"
  src = "contracts"
  verbosity = 3

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  optimizer = false

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  optimism = "${OPTIMISM_RPC_URL}"

  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
